# nginx-proxy/docker-compose.yml
version: '3.8'

services:
  mobile-api-proxy:
    image: nginx:stable-alpine
    container_name: helsan-mobile-api-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    restart: unless-stopped